import React from 'react'
import { useState } from "react";
import IMAGES from '../../assets/Images'
import { TiTickOutline } from 'react-icons/ti'
import { BiMap } from "react-icons/bi";
import { AiOutlineMail, AiOutlinePhone } from "react-icons/ai";
import { FooterNavbarData, FooterNavbarData2 } from "../navbar/NavbarData";
import { useNavigate } from "react-router-dom";

import { ClientsAndPartnersData } from '../home/ClientsAndPartnersData';
import "../../components/css/ClientAndPartnersStyle.css";


function Resource() {

  const [client, setClient] = useState(ClientsAndPartnersData );
  const [footernavdata, setFooterNavData] = useState(FooterNavbarData);
  const [footernavdata2, setFooterNavData2] = useState(FooterNavbarData2);

  const navigate = useNavigate();



  return (
    <div>
    <div className="mx-auto ">
        <div className="max-h-full relative ">
          <div className="absolute text-white bg-black/60  w-full h-full  flex flex-col justify-center items-center  ">
            <div className="tracking-wide">
              <h1 className="md:text-[50px] text-center capitalize selection:bg-[#222222]">
              Resource
              </h1>
            </div>
          </div>

          <div className="">
            <img
              src={IMAGES.image26}
              alt=""
              className=" w-full h-48 object-cover"
            />
          </div>
        </div>
      </div>



      <div className="  mt-20 mb-18 pb-8">
        <div className="md:max-w-[1180px] mx-auto selection:bg-[#222222] selection:text-white">
          <div className="grid lg:grid-cols-2 gap-6 pt-24 mr-4 ml-4">
            <div className="">
              <p className="uppercase underline underline-offset-8 text-blue-800 font-semibold pb-6">
              Resource 
              </p>
              <h1 className="text-4xl font-bold pb-6">
              What is Net Metering?
                            </h1>

                            <p className=" text-lg">
                            Net metering is a billing arrangement that allows homeowners and businesses with renewable energy systems, such as solar panels, to receive credit for the excess electricity they generate and feed back into the grid. Under a net metering program, a bi-directional meter tracks the energy generated by the renewable energy system and the energy consumed by the customer.
            </p>
           

             
            </div>

            <div className="">
              <img src={IMAGES.image95} alt="" className="pb-6 float-right" />
            
            </div>
          </div>

            <div className="grid lg:grid-cols-1 gap-6 pt-10 mr-4 ml-4">

            <div className="">
             

                            <p className=" text-lg">
                            consumed by the customer.

If the customer generates more electricity than they consume, the excess electricity is fed back into the grid and credited to their account. This credit can then be used to offset the cost of electricity that is consumed during periods when the renewable energy system is not generating electricity, such as at night or on cloudy days. Net metering policies vary by state and country, but it is a popular policy in many regions that encourage the adoption of renewable energy technologies.
            </p>
            <h1 className="mt-4 text-xl font-bold ">
            Benefits of Net Metering
                            </h1>

                            <ul className="list-none pt-2 text-lg">
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Financial savings:</b> Net metering allows homeowners and businesses to generate their own electricity and receive credit for the excess electricity they generate, which can help to offset their electricity bills. This can result in significant financial savings over time
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Increased use of renewable energy:</b> Net metering can encourage the adoption of renewable energy systems, such as solar panels, by making them more financially viable. This can help to reduce reliance on fossil fuels and promote a transition to cleaner energy sources.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Reduced greenhouse gas emissions:</b> By promoting the use of renewable energy, net metering can help to reduce greenhouse gas emissions and mitigate the impacts of climate change.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Improved grid stability:</b> Net metering can help to improve grid stability by reducing the strain on the grid during peak demand periods. This is because excess electricity generated by solar panels can be fed back into the grid, helping to balance the supply and demand of electricity.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Job creation:</b> The adoption of renewable energy systems through net metering can also create jobs in the renewable energy sector, contributing to the growth of the local economy.
                </li>
              </ul>

              <p>However, it is important to note that the benefits of net metering can vary depending on the specific policies and regulations in place, as well as the local electricity market conditions.</p>
            </div>

            </div>



        </div>
      </div>


      <div className="   mb-18 pb-24">
        <div className="md:max-w-[1180px] mx-auto selection:bg-[#222222] selection:text-white">
          <div className="grid lg:grid-cols-1 gap-6 pt-24 mr-4 ml-4">
            <div className="">
              <p className="uppercase underline underline-offset-8 text-blue-800 font-semibold pb-6">
              Resource 
              </p>
              <h1 className="text-4xl font-bold pb-6">
              Benefits of Hybrid Solar Plant
                            </h1>

                            <p className=" text-lg">
                            Hybrid solar plants offer a number of advantages over standalone solar power plants or other types of power plants. Here are some of the main advantages of hybrid solar plants: 
            </p>
           

             
            </div>

         

            <div className="">
             

                            

                            <ul className="list-none pt-2 text-lg">
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b>Increased energy production:</b> By combining different sources of energy, hybrid solar plants can produce more electricity than standalone solar power plants. This is because the additional energy source can be used to generate electricity when solar energy is not available, such as at night or during periods of low sunlight.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Improved energy reliability</b> Hybrid solar plants can provide a more reliable source of electricity than standalone solar power plants. This is because they can switch between different energy sources based on the availability of sunlight, wind, or other factors, ensuring a more consistent supply of electricity.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Reduced energy costs:</b> Hybrid solar plants can be more cost-effective than standalone solar power plants, as they can use the most cost-effective source of energy at any given time. This can help to reduce the overall cost of electricity generation.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Increased energy security:</b> By using multiple sources of energy, hybrid solar plants can reduce the reliance on a single source of energy. This can improve energy security and reduce the risk of power outages.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Reduced carbon emissions: </b> Hybrid solar plants can help to reduce carbon emissions, as they can use renewable energy sources such as solar and wind power, as well as non-renewable sources such as natural gas or diesel fuel. By reducing the reliance on fossil fuels, hybrid solar plants can help to mitigate the impact of climate change.
                </li>
              </ul>

              <p>In summary, hybrid solar plants offer a range of benefits, including increased energy production, improved energy reliability, reduced energy costs, increased energy security, and reduced carbon emissions. These benefits make hybrid solar plants an attractive option for meeting the energy needs of communities and businesses around the world.</p>
            </div>

            </div>



        </div>
      </div>


      <div className="md:max-w-[1180px] mt-20 mx-auto selection:bg-[#222222] selection:text-white">
        <div className="grid lg:grid-cols-2 gap-6 mr-4 ml-4">
          <div className="">
            <img
              src={IMAGES.image96}
              alt="not found"
              className="w-full "
            />
          </div>

          <div className="">
            <p className="uppercase underline underline-offset-8 text-blue-600 font-semibold pb-6">
            Resource
            </p>
            <h1 className="text-4xl font-bold ">Group Net Metering</h1>
            <p className="pt-6 text-lg">
            Group net metering is a policy that allows multiple customers or energy users to share the benefits of a single renewable energy system. In group net metering, the excess energy generated by the renewable energy system is credited to the energy bills of multiple customers or energy users who are part of a group or community.
            
Under group net metering, a single renewable energy system, such as a solar or wind power system, can generate electricity for multiple customers who are connected to the same distribution network or grid. The excess energy generated by the renewable energy system is fed back into the grid, and the energy credits are shared among the members of the group or community.
<br />
<br />
Group net metering can benefit a wide range of customers, including households, small businesses, and community organizations. It can help to lower energy bills, reduce the reliance on fossil fuels, and promote the use of renewable energy sources.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-1 gap-6 pt-10 mr-4 ml-4">

<div className="">
<h1 className=" text-xl font-bold ">
The main advantages of group net metering include:                </h1>

                <ul className="list-none pt-2 text-lg">
    <TiTickOutline
      size={20}
      className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
    />
    <li className="pl-6 pb-4">
      {" "}
     <b>Reduced energy costs:</b> Group net metering allows customers to share the benefits of a single renewable energy system, which can help to reduce energy costs for all members of the group.
    </li>
    <TiTickOutline
      size={20}
      className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
    />
     <li className="pl-6 pb-4">
      {" "}
      <b>Increased access to renewable energy: </b> Group net metering can make it easier for households, small businesses, and community organizations to access and benefit from renewable energy sources, even if they are unable to install their own renewable energy systems.
    </li>
    <TiTickOutline
      size={20}
      className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
    />
    <li className="pl-6 pb-4">
      {" "}
      <b>Promotion of community energy: </b> Group net metering can promote community energy by encouraging the development of shared renewable energy systems that benefit multiple customers and promote a sense of community ownership.
    </li>
   
    <TiTickOutline
      size={20}
      className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
    />
    <li className="pl-6 pb-4">
      {" "}
     <b> Reduced carbon emissions:</b>  Group net metering can help to reduce carbon emissions by promoting the use of renewable energy sources, such as solar or wind power, which have lower greenhouse gas emissions than fossil fuels.
    </li>
    
     
  </ul>

  <p>In summary, group net metering is a policy that allows multiple customers or energy users to share the benefits of a single renewable energy system. It can help to lower energy costs, increase access to renewable energy, promote community energy, and reduce carbon emissions.</p>
</div>

</div>


      </div>

      <div className="  mt-20 mb-18 pb-8">
        <div className="md:max-w-[1180px] mx-auto selection:bg-[#222222] selection:text-white">
          <div className="grid lg:grid-cols-2 gap-6 pt-24 mr-4 ml-4">
            <div className="">
              <p className="uppercase underline underline-offset-8 text-blue-800 font-semibold pb-6">
              Resource 
              </p>
              <h1 className="text-4xl font-bold pb-6">
              Virtual Net Metering
                            </h1>

                            <p className=" text-lg">
                            Virtual net metering is a policy that allows multiple customers or energy users to benefit from a single renewable energy system that is not physically located on their property. Under virtual net metering, the excess energy generated by the renewable energy system is credited to the energy bills of multiple customers or energy users who are connected to the same distribution network or grid.
<br />
<br />
Virtual net metering is particularly useful in situations where it is not possible or practical for customers to install their own renewable energy systems, such as in apartment buildings or commercial properties. In these cases, a single renewable energy system, such as a solar or wind power system, can generate electricity for multiple customers who are connected to the same distribution network or grid.
            </p>
           

             
            </div>

            <div className="">
              <img src={IMAGES.image97} alt="" className="pb-6 float-right" />
            
            </div>   
          </div>

            <div className="grid lg:grid-cols-1 gap-6 pt-10 mr-4 ml-4">

            <div className="">
             
            <h1 className=" text-xl font-bold ">
The main advantages of group net metering include:                </h1>
                            <ul className="list-none pt-2 text-lg">
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b>Increased access to renewable energy:</b>Virtual net metering allows customers who are unable to install their own renewable energy systems to benefit from the use of renewable energy sources, such as solar or wind power.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Reduced energy costs: </b> Virtual net metering can help to reduce energy costs for customers who are part of a group or community that benefits from a single renewable energy system.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Promotion of renewable energy:</b>  Virtual net metering can promote the use of renewable energy sources, such as solar or wind power, by making it easier and more accessible for customers to benefit from these sources of energy.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Reduced carbon emissions: </b> Virtual net metering can help to reduce carbon emissions by promoting the use of renewable energy sources, which have lower greenhouse gas emissions than fossil fuels.
                </li>
                
              </ul>

              <p>In summary, virtual net metering is a policy that allows multiple customers or energy users to benefit from a single renewable energy system that is not physically located on their property. It can help to increase access to renewable energy, reduce energy costs, promote renewable energy, and reduce carbon emissions.</p>
            </div>

            </div>



        </div>
      </div>




      <div className="  mt-20 mb-18 pb-8">
        <div className="md:max-w-[1180px] mx-auto selection:bg-[#222222] selection:text-white">
          <div className="grid lg:grid-cols-1 gap-6 pt-24 mr-4 ml-4">
            <div className="">
              <p className="uppercase underline underline-offset-8 text-blue-800 font-semibold pb-6">
              Resource 
              </p>
              <h1 className="text-4xl font-bold pb-6">
              Benefits of Rooftop Solar
                            </h1>

                          
             
            </div>

              
          

            <div className="">
             
            <h1 className=" text-xl  ">
            There are many benefits to installing a rooftop solar power plant, including:               </h1>
                            <ul className="list-none pt-2 text-lg">
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b>Reduced electricity bills: </b>By generating electricity from the sun, a rooftop solar power plant can significantly reduce or eliminate a home or business's dependence on grid electricity, resulting in lower electricity bills.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Increased energy independence: </b> Rooftop solar power plants can provide energy independence, allowing homeowners and businesses to generate their own electricity and reducing their reliance on centralized power generation and distribution.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                  <b>Reduced carbon footprint:</b>   By generating electricity from renewable sources, rooftop solar power plants can help reduce the use of fossil fuels, thereby lowering greenhouse gas emissions and mitigating climate change.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Increased property value: </b> Homes and businesses with rooftop solar power plants are increasingly in demand and can command higher prices due to the perceived value of owning a sustainable property.
                </li>


                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b> Incentives and tax benefits:  </b> Governments and utilities often offer incentives and tax credits to encourage the adoption of rooftop solar power plants, making them more affordable for homeowners and businesses.
                </li>

                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b>Reliability and durability: </b> Rooftop solar power plants are designed to be durable and reliable, with solar panels having a lifespan of up to 25 years or more, requiring minimal maintenance.
                </li>
                <TiTickOutline
                  size={20}
                  className="float-left mt-1 text-blue-800 border border-black rounded-full hover:bg-[#2331BC] hover:text-white"
                />
                <li className="pl-6 pb-4">
                  {" "}
                 <b>Redundancy and backup power: </b>  Rooftop solar power plants can provide redundancy and backup power in the event of a grid outage, ensuring that homes and businesses have access to electricity when they need it.
                </li>
                
              </ul>

              <p>In summary, the benefits of a rooftop solar power plant include reduced electricity bills, increased energy independence, a reduced carbon footprint, increased property value, incentives and tax benefits, reliability and durability, and redundancy and backup power.</p>
            </div>

            </div>



        </div>
      </div>



      {/* Our Clients & Partners start from here */}

      <div className="bg-gray-100  mb-16 pb-24  ">
        <h1 className="text-center text-4xl font-bold pt-16 selection:bg-gray-700 selection:text-white ">
          Our Clients & Partners
        </h1>
        <div className="container ml-40 mr-40 mt-24 w-auto h-auto">
          {/* <div className="max-w-[1240px] mx-auto grid grid-cols-8">
       <div>
        <img src={IMAGES.image33} alt="" className="" />
       </div>

      </div> */}
          <div className="  mx-auto   slider-track gap-8 ">
            {client.map((item4, index4) => (
              <div key={index4} className="">
                <img src={item4.clients} alt="" className="" />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Our Clients & Partners end from here */}

      {/* Footer start from here */}

      <div className="max-w-[1240px] mx-auto border-b-2 border-gray-200 mb-10 selection:bg-[#222222] selection:text-white ">
        <div className=" grid lg:grid-cols-4 gap-2  m-0 pb-6 pt-10">
          <div className="  h-auto md:grid-cols-6 pl-5 pr-5 pb-6">
            <div className="border-b-4 border-b-gray-600  h-10 mt-auto mb-auto   text-xl ">
              {" "}
              About Company
            </div>
            <p className="pt-8 text-lg">
              We are on a mission to make this planet a better place to live and
              we are committed to make clean energy available to all which is,
              Renewable, Reliable, and Affordable.
            </p>

            <div className="pt-4">
              <ul className=" inline-flex gap-4">
                <li className="hover:bg-[#2331BC] bg-gray-400 rounded-full p-1 cursor-pointer">
                  <img src={IMAGES.image56} alt=" " />{" "}
                </li>
                <li className="hover:bg-[#2331BC] bg-gray-400 rounded-full p-1 cursor-pointer">
                  <img src={IMAGES.image57} alt=" " />{" "}
                </li>
                <li className="hover:bg-[#2331BC] bg-gray-400 rounded-full p-1 cursor-pointer">
                  <img src={IMAGES.image58} alt=" " />{" "}
                </li>
              </ul>
            </div>
          </div>

          <div className="  h-auto md:grid-cols-6  pl-5 pr-5 pb-6">
            <div className="border-b-4 border-b-gray-600  h-10 mt-auto mb-auto   text-xl  ">
              {" "}
              Quick Links
            </div>

            <ul className="pt-8  space-y-2 ">
            {footernavdata.map((item5, index5) => (
              <div key={index5}>
           
              <li onClick={() => navigate(`${item5.url}`)} className='cursor-pointer uppercase'>{item5.nav}</li>
              </div>
              ))}
            </ul>
          </div>

          <div className="  h-auto md:grid-cols-6  pl-5 pr-5 mt-10 pb-6">
          <ul className="pt-8 leading-8">
            {footernavdata2.map((item6, index6) => (
              <div key={index6}>
           
              <li onClick={() => navigate(`${item6.url}`)} className='cursor-pointer uppercase'>{item6.nav}</li>
              </div>
              ))}
            </ul>
          </div>

          <div className=" h-auto md:grid-cols-6 text-left pl-5 pr-5 pb-6">
            <div className="border-b-4 border-b-gray-600  h-10 mt-auto mb-auto   text-xl  ">
              {" "}
              Contact Us
            </div>

            <ul className="list-none pt-8 text-lg">
              <BiMap size={20} className="float-left mt-1 text-blue-800 " />
              <li className="pl-8 pb-4">
                STPI Building, Plot-8, Namkum Industrial Area, Ranchi, Jharkhand
                - 834010
              </li>
              <AiOutlineMail
                size={20}
                className="float-left mt-1 text-blue-800 "
              />
              <li className="pl-8 pb-4 ">
                info@sologixenergy.in, amit@sologixenergy.in,
                anil@sologixenergy.in
              </li>
              <AiOutlinePhone
                size={20}
                className="float-left mt-1 text-blue-800 "
              />
              <li className="pl-8">+91-8287766474, +91-7838498478</li>
            </ul>
          </div>
        </div>
      </div>

      {/* Footer end from here */}

      {/* Copyright start from here */}

      <div className="mb-12 selection:bg-[#222222] selection:text-white  pl-5 pr-5">
        <p className="text-center text-lg">
          Copyright © 2023 Sologix. All Rights Reserved. (Made by Kumar Atul
          Jaiswal)
        </p>
      </div>

      {/* Copyright end from here */}


    </div>
  )
}

export default Resource